# バッテリー報告を有効にする！。
CONFIG_ZMK_BATTERY_REPORTING=y
# Windowsでの％表示問題を回避
CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=n
# 左右分離型のバッテリー情報を統合する
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
